name: Quality
on: [push, pull_request]
jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.0'
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go mod download
      - name: Install chrome
        uses: browser-actions/setup-chrome@latest
      - name: Install wasmbrowsertest
        run: |
          git clone -b add-httpbin-endpoints https://github.com/mlctrez/wasmbrowsertest /tmp/wasmbrowsertest
          go mod -C /tmp/wasmbrowsertest download
          go build -C /tmp/wasmbrowsertest -o $(go env GOPATH)/bin/go_js_wasm_exec
      - name: Run Unit tests
        run: |
          go test -race -covermode atomic -coverprofile=covprofile_nowasm .
      - name: Run Unit tests using wasmbrowsertest
        run: |
          GOOS=js GOARCH=wasm go test -cover -covermode atomic -test.coverprofile=covprofile_wasm ./...
      - name: Install gocovmerge
        run: |
          go install github.com/wadey/gocovmerge@latest
      - name: Merge coverage
        run: |
          gocovmerge covprofile_nowasm covprofile_wasm > covprofile
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github